import Breadcrumb from "@/components/Breadcrumb";
import Footer from "@/components/Footer";
import Header from "@/components/Header";
import { Container } from "@mui/material";
import Head from "next/head";

const MainLayout = ({ children }) => {
  return (
    <>
      <Head>
        <title>Hockey</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={`wrapper`}>
        <Header />
        <main style={{ marginTop: 80 }}>
          <Container maxWidth="md">
            <Breadcrumb />
            {children}
          </Container>
        </main>
        <Footer />
      </div>
    </>
  );
};

export default MainLayout;
